spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: demo
    password: "demo_pass"
    url: jdbc:postgresql://${SBOOT_DEMO_PG_PORT_5432_TCP_ADDR}:${SBOOT_DEMO_PG_PORT_5432_TCP_PORT}/sboot_demo
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  port: 8180
  contextPath: /SpringIODemo

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: true
  hbm2ddl:
    auto: none

app:
  version: vx.x-default

togglz:
#  enabled: true # Enabled by default
#  featureEnums:
#    com.asimio.demo.togglz.config.FeatureToggles
  console:
    enabled: true
    path: /app-admin
    secured: false
    use-management-port: false
  features:
    TEXT_BASED_SEARCH_VIA_ELASTIC_SEARCH:
      enabled: true
    MOBILE_NUMBER_FIELD:
      enabled: true
    CONTENT_RETRIEVAL_VIA_CMS:
      enabled: false
    USE_NEW_SOMESERVICE:
      enabled: true

info:
  app:
    name: @project.artifactId@
  build:
    version: @project.version@

redisHost: redis_db

togglzPrefix: liquiBaseApp_togglz